# Generated by Django 5.0.6 on 2024-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(related_name='projects', to='api.stack'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='icon_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
